version: '3'

services:
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension

  cep:
    container_name: cep
    build: 
      context: .
      dockerfile: cep.Dockerfile
    environment:
      - OTEL_SERVICE_NAME=microservice-cep
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "8080:8080"
    depends_on:
      - zipkin-all-in-one
      - otel-collector
      - prometheus

  weather:
    container_name: weather
    build: 
      context: .
      dockerfile: weather.Dockerfile
    environment:
      - OTEL_SERVICE_NAME=microservice-weather
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
    ports:
      - "8181:8181"
    depends_on:
      - zipkin-all-in-one
      - otel-collector
      - prometheus